puppetlabs/puppetlabs-pe_status_check

- spec/acceptance/self_service_spec.rb
prior to this commit NOOP was left on which impacted later tests
> correction for ordering and state management in testing

- README.md
- REFERENCE.md
- lib/facter/self_service.rb
- manifests/init.pp
- spec/acceptance/self_service_spec.rb
> (maint) Minor linting

- lib/facter/self_service.rb
- spec/acceptance/self_service_spec.rb
Adds in checks for catalog application and last run time  sanity
> (SUP-2861) Puppet Agent Health Checks

- .github/pull_request_template.md
This commit adds a PR template to the repo. This is a short lived
template that will be removed after the initial development of this
module.
> (maint) Add a PR template for the repo

- README.md
- lib/facter/self_service.rb
- spec/acceptance/self_service_spec.rb
> (SUP-2915) Check if max-queued-requests is configured to above 150

- spec/acceptance/self_service_spec.rb
> Fixing intermittent issue with test for S0036

- lib/facter/self_service.rb
Adding confinement to S0036 to not run on postgres nodes
> Add confinement to S0036

- lib/facter/self_service.rb
- lib/shared/puppet_self_service.rb
- spec/acceptance/self_service_spec.rb
- spec/spec_helper_acceptance_local.rb
> (SUP-2896) Check Avg Free JRubies

- README.md
> (SUP-3004) correct formating issue in readme

- lib/facter/agent_status_check.rb
Adds debug information to AS0002's error handling
> add better error handling to AS0002

- README.md
- plans/agent_summary.pp
prior to this commit there was a plan to summarise the pe_status_check fact, this commit adds a second plan for agent_status_check
> (SUP-3229) Summary Plan for agents

- lib/facter/pe_status_check_role.rb
There may be an issue loading 'puppet' or getting the settings during
installation, so return 'unknown' if so.
> (SUP-3381) Add error handling to role fact

- lib/facter/pe_status_check.rb
- lib/facter/pe_status_check_role.rb
Adds in support for primaries without postgres server
> SUP-3398 legacy primary support

- README.md
This commit adds the following updates to the readme:
- Explains the fact confinements more clearly
- Defines the pe_status_check_role fact
- adds in example pql queries
> (SUP-3400)(SUP-3401)(SUP-3402) Update Readme to explain facts further

- lib/facter/pe_status_check.rb
s0036 and s0040 where duplicated
> Remove duplicate Chunks

- .devcontainer/README.md
- Gemfile
- lib/facter/pe_status_check.rb
- metadata.json
- spec/default_facts.yml
in the old licence format licence_type was not a field and is the equivalent of perpetual
> (Sup-3700) Handle missing licence type

- lib/facter/agent_status_check.rb
Avoid having to list all processes in the process table in order to associate the socket with pxp-agent.
> (#170) Improve agent_status_check.AS002 performance

- lib/facter/pe_status_check.rb
> (SUP-3786) Update s00036 to not trigger on 150

- .fixtures.yml
- .github/workflows/pe_nightly.yml
Testing nightly and peadm workflow
> Testing nightly & peadm workflow

- .fixtures.yml
> Update version of node manager in fixtures

- data/static.yaml
Prior to this commit S0038 lacked a definition lookup in hiera
> (SUP-4275) Update Hiera definition of S0038

- data/static.yaml
- lib/facter/pe_status_check.rb
- spec/acceptance/pe_status_check_spec.rb
This PR contains modifications made to `pe_status_check.rb`, `static.yaml` and `pe_status_check_spec.rb`.  
This not checks against primary only as opposed to the other services, with test S0004 incremented and the test replicated for S0020.
> SUP-4458 addition of test S0020 to test console-service endpoint

- lib/facter/pe_status_check_role.rb
This makes the code a bit cleaner/shorter and saves us one variable.
> pe_status_check_role: Cleanup class matching

- lib/facter/pe_status_check.rb
> (SUP-4955) Wildcard Operator Added for file license ingestion

- CODEOWNERS
> Update CODEOWNERS To reflect new ownership
