puppetlabs/puppetlabs-pe_status_check

lib/facter/self_service.rb
lib/shared/puppet_self_service.rb

Prior to this commit, the logic for checking the service state depended
on running the `puppet resource` face from an exec. This commit adds
some code to use `Puppet::Type` and provides methods to check the
service states in a shared module.

(maint) Move service logic to a module

---

lib/facter/self_service.rb
lib/shared/puppet_self_service.rb
spec/acceptance/self_service_spec.rb

Prior to this commit lengthy statements of node confinement had to be made per chunk
Post this update, the whole fact will be confine to just PE infra nodes, and each chunk can be confined to node types found in out standard / large and XL deployments
primary / replica/ compiler or postgres

Adds in PE node confinement types and more status checks

---

lib/facter/self_service.rb
lib/shared/puppet_self_service.rb
spec/acceptance/self_service_spec.rb

Prior to this PR, S0007 used existing facts to check the free disk
space. This PR adds a shared method to check the disk space of an
arbitrary filesytem path and uses it for S0007 and S0008.
Prior to this PR, the acceptance test was checking that all elements
in the fact hash were not false, however it did not specify the number
of elements in the hash This could lead to a scenario where a chunk is
missing and still passes. This PR checks the explicit number of
chunks in the hash.

Adds a filesystem free method

---

manifests/init.pp

Prior to this commit, the class would fail with an error if the
self_service fact was not present. This commit updates the code to
handle a missing self_service fact.
This fixes an issue with the manifest where the `self_service` fact doesn't exist, such as being classified on a non-PE infra node. It also fixes issues where the fact may not be in place when impact analysis runs or other CI-type testing.

(fix) Do not filter on Undef

---

.fixtures.yml

Per recent changes to [GH security](https://github.blog/2021-09-01-improving-git-protocol-security-github/), updated repo source protocols in `.fixures.yaml`.
* Updated `.fixtures.yaml` to move public repo sources from `git` to `https` protocol.

(SUP-2923) Replace unencrypted git protocol in .fixtures.yaml

---

lib/facter/self_service.rb

Prior to this commit, S0006 ran on all infra nodes. The puppet metrics
collector should only run on the primary server in most configurations,
so it should be restricted to the primary. This commit restricts S0006
to the primary server.
Resolves #52

(GH-52) Restrict S0006 to primaries

---

.github/pull_request_template.md

Prior to this commit, the PR template had some items that are no longer
relevant. This commit removes those entries from the PR template.

(maint) Remove contest information from the PR template

---

lib/facter/agent_self_service.rb
spec/acceptance/agent_self_service_spec.rb

This fact allows for the automation of tasks relating to expiring agent certs in the PE population, by reporting "true" to the puppetdb, if a host cert is due to expire within 90 days

Adding Agent only Fact check for expiring host cert

---

spec/acceptance/self_service_spec.rb

Fix for [issue 63](https://github.com/puppetlabs/puppetlabs-self_service/issues/63). Replaced the fact numbers with the correct one.

(Issue #63) - Fixed the fact check in acceptance testing 

---

spec/acceptance/self_service_spec.rb
spec/spec_helper_acceptance_local.rb

Prior to this commit, there was the possibility that the puppet agent
would be running during the acceptance testing, which could change the
results of the testing. This commit disables the puppet agent by
default.

(maint) Stop puppet agent runs during testing

---

lib/facter/self_service.rb
lib/shared/puppet_self_service.rb
spec/acceptance/self_service_spec.rb

Prior to this PR, S0004 was using puppet infra status to work out Infrastructure services and it was too slow to produce result.
Post this, S0004 uses a shareable NETT::HTTP function to work out localhost (127.0.0.1) services estate.

(SUP-2945) Updating S0004 to call the services API

---

Gemfile

New version of oktokit is not compatible with change_log_generator only current resolution is to bin the version.
Or release workflow will get rate limiting errors
May need reverted at a later date

Pin octokit version to fix auto release workflowe

---

lib/facter/self_service.rb
spec/acceptance/self_service_spec.rb

Prior to this commit, we parsed puppetserver.log log check for 503
errors, but this can be determined from the access logs without the risk
of parsing a huge file with many custom code errors and warnings.  This
commit uses an Apache regex to check if puppetserver-access.log has 503
return codes.

(SUP-2918) Update S0039 to parse server access log

---

lib/shared/pe_status_check.rb

This commit uses 'module_function' instead of self.<function> for
function declarations.  This makes functions available as module
functions to the class that includes the module.

Module function

---

lib/facter/pe_status_check.rb
spec/acceptance/pe_status_check_spec.rb

Prior to this commit, S0039 would stay in the false state until the Access log rotated, which did not reflect the current status.
Now the alert is only valid, if the 503 message was sent in the last run interval

(SUP-3099) Only Alert on 503 messages sent in last run interval

---

lib/facter/pe_status_check.rb

Prior to this commit, S0039 could fail if a line in the access log was
not in common log format, which would result in [] being called on a nil
object.  This commit checks that we have a match, as well as the named
capture groups.

Check for non-nil match in S0039

---

lib/shared/pe_status_check.rb

Changes made to PE in 2021.5 caused replicas to run tests intended for a primary, this resolves that issue

(SUP-3116) Fix replica Detection in 2021.5

---

lib/shared/pe_status_check.rb

Prior to this commit the presence of the service file "/pe-pgsql/pe-postgresql" was considered in the determination of the node type, in 2021.5 this service file does not exist.
PSQL nodes are now simply a negative check for the other node types

(SUP-3122) Fix PSQL node detection in 2021.5

---

spec/acceptance/pe_status_check_spec.rb

This commit bumps the expected number of chunks in the pe_status_check
fact to the correct number, 30.

Bump pe_status_check count to 30

---

lib/facter/agent_status_check.rb

The same test command used by other Linux families works on SLES 11, 12, and 15. This adds the "Suse" family to the list of other supported Linux distributions.
Also, a typo noted in the warning message was fixed.

Add Suse support to AS002

---

.puppet-lint.rc
.sync.yml
README.md
REFERENCE.md
Rakefile
metadata.json
plans/infra_summary.pp

This commit changes the output of the plan format to have a summary and
details. It aligns the parameters with the init.pp class to ensure that
the plan can handle excluding checks.
Output examples:
```
{
"nodes": {
"details": {
"puppet.example.com": {
"Failed Test Count": 0,
"Failed Test Details": [],
"Passing Tests Count": 28
}
},
"failing": [],
"passing": [
"puppet.example.com"
]
},
"errors": {
"agent.example.com": "Missing the 'pe_status_check' fact"
},
"passed": false,
"failing_node_count": 1,
"passing_node_count": 1
}
```
```
{
"nodes": {
"details": {
"puppet.example.com": {
"Failed Test Count": 0,
"Failed Test Details": [],
"Passing Tests Count": 28
}
},
"failing": [],
"passing": [
"puppet.example.com"
]
},
"errors": {},
"passed": true,
"failing_node_count": 0, …
```

(SUP-3005) Update plan output format

---

lib/facter/pe_status_check.rb
lib/facter/pe_status_check_role.rb
lib/shared/pe_status_check.rb

This commit introduces a new fact, pe_status_check_role, to determine
a node's role in a PE infrastructure.  We do this using the list of
classes in the classfile setting and checking for certain PE profile
classes.

(SUP-3315) Use cached state to determine node role

---

lib/facter/agent_status_check.rb
lib/facter/pe_status_check.rb
lib/shared/pe_status_check.rb

This commit adds a timeout of 2 seconds for Facter's .execute method.
It also standardizes some of the error handling.

(SUP-3426) Use shorter timeout for facter execute

---

metadata.json

Prior to this commit it wasnt indicated that windows was supported for agent_status_check
Also added newly added supported OS versions

(SUP-3423) Update metadata to reflect supported agent OS

---

README.md
REFERENCE.md
lib/facter/agent_status_check.rb
lib/shared/pe_status_check.rb
manifests/agent_status_enable.pp
manifests/init.pp
spec/classes/agent_status_enable_spec.rb
spec/default_facts.yml

Prior to this commit, the agent_status_check fact would sync to all nodes immediately following module installation.
Customers prefer to target and the fact specifically so a class has been added to enable this

(SUP-3450) make agent_status_check collection optional

---

lib/facter/agent_status_check.rb
lib/facter/pe_status_check.rb

Updated the ss commands in the pe_status check and the agent status check to not pipe commands as it resulted in stuck processes not getting killed.

(SUP-3442) Update ss commands so timeout kills the process

---

lib/facter/agent_status_check.rb
lib/facter/pe_status_check.rb

Prior to this commit if hostcert resolved to a path that wasn't present, the entire agent_status_check fact would fail.
This could happen if certname was set in the agent section.
This handles the path presented by hostcert not being presenting by gracefully skipping that one chunk

(SUP-3452) Handle hostcert path missing

---

README.md
data/static.yaml
lib/facter/agent_status_check.rb
plans/agent_summary.pp

This commit adds in a new agent check to ensure the certname configuration only exists in the [main] section of the puppet.conf

(Sup-3465) check for certname in incorrect configuration section

---

lib/facter/pe_status_check.rb

This commit checks that the free_jrubies value is non-nil and not a
string, then converts it to a float for the comparison.  This is because
the api may return a string "NaN" in some circumstances.

(SUP-3491) Cast free_jrubies value to float

---

lib/shared/pe_status_check.rb

Prior to this commit, this method would emit warnings during
installation or other times where Puppet server may not be available.
This commit lowers it to debug level to help avoid confusion during
upgrades.

Change log level in http_get to debug

---

lib/facter/pe_status_check.rb

Prior to this commit, if the puppetserver access logs where incorrectly formatted, facter resolution of the pe_status_check fact would end, and an error would be printed.
Following this update, the fact will resolve correctly and emit a warning about the formatting of the file.
Is of particular importance until https://tickets.puppetlabs.com/browse/PE-34726 is resolved, as locales other then en_gb and en_us cause issues with the access log formats

(SUP-3724) error handling for access log parsing

---

lib/facter/pe_status_check.rb

Specifying the 'status-service' endpoint in the URL path to narrow the status scope significantly decreases the query time on large PE environments to avoid hitting the 2 second request timeout.

(#172) Improve query time on S0026

---

lib/facter/pe_status_check.rb

Adds a break to the rescue statement in the loop in S0039 so if the time is in a unreadable format we only show the warning once instead of for every line it occurs.

(SUP-3777) Stop loop in S0039 if log is in unreadable format

---

data/static.yaml
lib/facter/pe_status_check.rb

This commit adds error handling to S0044 to guard against Facter failures such as a NoMethodError for the set_in_section method.

(SUP-4282) add error handling to S0044

---

spec/acceptance/pe_status_check_spec.rb

This should remove opportunities for s0019 to false flag an acceptance test
it is still possible for it to fail:
check no pe_status_check fact is false
As that will require a lot of work to resolve, but this should reduce possible incidents by 1/3

(SUP-4316)  remove problematic test fo s0019

---

.rubocop.yml
lib/facter/pe_status_check.rb

IO.read is potentially unsafe when called with special characters, which isn't an issue here. Use File.read to avoid any future issues.

Enable security cops

---

README.md
hiera.yaml
plans/agent_summary.pp
plans/infra_summary.pp

Work done and tested within PE_Status_Check, lookup added to `pe_status_check::infra_summary` and `pe_status_check::agent_summary` plans and tested within PE_Console

(SUP-3709) - Indicator Exclusion using code manager and Hiera lookup

---

lib/facter/pe_status_check.rb

S0039 Indicator was producing an error when there was no existing `puppetserver-access.log` file located within `/var/log/puppetlabs/puppetserver`.
This PR resolves the error messages being highlighted by https://github.com/puppetlabs/puppetlabs-pe_status_check/issues/213 - adding in a condition that will bypass the indicator in the event of a non existent file.

(SUP-4714) Check if logfile exists during runtime of S0039

---

README.md
REFERENCE.md
plans/infra_role_summary.pp

This plan returns a hash of data with all PE infra nodes and their role.

Add infra_role_summary plan

---

lib/facter/pe_status_check.rb
spec/acceptance/pe_status_check_spec.rb

(SUP-4929) Update to S0022 for handling license files with .key and .lic file

---

lib/facter/pe_status_check.rb

Add string substitution to S0039 to accommodate unicode CLDR change from Sep to Sept for %b in September

(SUP-4990) S0039 Accommodate parsing of unicode dates in September

---

README.md
plans/agent_state_summary.pp

It's possible that a Puppet Agent was stopped or disabled and all old reports were garbage collected from PuppetDB. The node still exists in PuppetDB, but when checking for a report the timestamp is null:
```
puppet query nodes[certname,report_timestamp]{}
```
```json
[
{
"certname": "pe.tim.local",
"report_timestamp": "2024-09-30T13:21:17.042Z"
},
{
"certname": "pe2.tim.local",
"report_timestamp": null
}
]
```
Previously we always assumed that `report_timestamp` has a valid timestamp. With this patch we explicitly validate the timestamp and count nodes withhout a timestamp as unhealthy.
Now with the fix:
```
puppet plan run pe_status_check::agent_state_summary --environment peadm log_healthy_nodes=true log_unhealthy_nodes=true
```
```json
{
"responsive": [
"pe.tim.local",
"pe2.tim.local" …
```

(#236) agent_state_summary: Count nodes without report as unhealthy

---

plans/agent_state_summary.pp

The attribute `cached_catalog_status` on the `/nodes` endpoint will be `null` for nodes without a catalog in PuppetDB:
```
puppet query 'nodes[certname,latest_report_noop,latest_report_corrective_change,cached_catalog_status,latest_report_status,report_timestamp]{}'
```
```
[
{
"cached_catalog_status": null,
"certname": "pe2.tim.betadots.training",
"latest_report_corrective_change": null,
"latest_report_noop": null,
"latest_report_status": null,
"report_timestamp": null
}
]
```

(#236) agent_state_summary: Check if cached_catalog_status is null

---

lib/facter/agent_status_check.rb

The list of files in /proc/[0-9]*/cmdline can change as processes start or terminate between the Dir.glob and File.read operations

fix: prevent random failures in agent_status_check

---

plans/agent_state_summary.pp

previously, when running `pe_status_check::agent_state_summary`, the result didn't only contain the certnames, but also additional data:`
without this patch (one unresponsive node, one without reports at all):
```json
{
"noop": [
],
"corrective_changes": [
],
"used_cached_catalog": [
],
"failed": [
],
"changed": [
],
"unresponsive": [
{
"certname": "pe.tim",
"latest_report_noop": false,
"latest_report_corrective_change": false,
"cached_catalog_status": "not_used",
"latest_report_status": "unchanged",
"report_timestamp": "2024-12-05T13:41:55.483Z"
}
],
"no_report": [
"agent.tim"
],
"responsive": [
"pe.tim"
],
"unhealthy": [
{
"certname": "pe.tim",
"latest_report_noop": false,
"latest_report_corrective_change": false,
"cached_catalog_status": "not_used",
"latest_report_status": "unchanged", …
```

agent_state_summary: Properly handle nodes without reports/responses
